Update sentinel

diff --git a/sentinel/files/usr/bin/sentinel b/sentinel/files/usr/bin/sentinel
--- a/sentinel/files/usr/bin/sentinel
+++ b/sentinel/files/usr/bin/sentinel
@@ -1205,67 +1205,54 @@ import_community_subnet_lists() {
 
 import_community_service_subnet_list_handler() {
     local service="$1"
-    local URL=""
 
     case "$service" in
-    twitter)
-        URL="$SUBNETS_TWITTER"
+    "twitter")
+        URL=$SUBNETS_TWITTER
         ;;
-    meta)
-        URL="$SUBNETS_META"
+    "meta")
+        URL=$SUBNETS_META
         ;;
-    telegram)
-        URL="$SUBNETS_TELEGRAM"
+    "telegram")
+        URL=$SUBNETS_TELEGRAM
         ;;
-    roblox)
-        URL="$SUBNETS_ROBLOX"
+    "cloudflare")
+        URL=$SUBNETS_CLOUDFLARE
         ;;
-    cloudflare)
-        URL="$SUBNETS_CLOUDFLARE"
+    "hetzner")
+        URL=$SUBNETS_HETZNER
         ;;
-    hetzner)
-        URL="$SUBNETS_HETZNER"
+    "ovh")
+        URL=$SUBNETS_OVH
         ;;
-    ovh)
-        URL="$SUBNETS_OVH"
+    "digitalocean")
+        URL=$SUBNETS_DIGITALOCEAN
         ;;
-    digitalocean)
-        URL="$SUBNETS_DIGITALOCEAN"
+    "cloudfront")
+        URL=$SUBNETS_CLOUDFRONT
         ;;
-    cloudfront)
-        URL="$SUBNETS_CLOUDFRONT"
-        ;;
-    discord)
-        URL="$SUBNETS_DISCORD"
-
+    "discord")
+        URL=$SUBNETS_DISCORD
         nft_create_ipv4_set "$NFT_TABLE_NAME" "$NFT_DISCORD_SET_NAME"
-
-        nft add rule inet "$NFT_TABLE_NAME" mangle \
-            iifname "@$NFT_INTERFACE_SET_NAME" \
-            ip daddr "@$NFT_DISCORD_SET_NAME" \
-            udp dport 50000-65535 \
-            meta mark set 0x105 counter 2>/dev/null
+        nft add rule inet "$NFT_TABLE_NAME" mangle iifname "@$NFT_INTERFACE_SET_NAME" ip daddr \
+            "@$NFT_DISCORD_SET_NAME" udp dport '{ 50000-65535 }' meta mark set 0x105 counter
         ;;
-    *)
-        return 0
-        ;;
+    *) return 0 ;;
     esac
 
-    [ -z "$URL" ] && return 0
-
-    local tmpfile subnets http_proxy_address
-    tmpfile="$(mktemp)"
+    local tmpfile detour http_proxy_address subnets
+    tmpfile=$(mktemp)
     http_proxy_address="$(get_service_proxy_address)"
 
-    download_to_file "$URL" "$tmpfile" "$http_proxy_address" || {
-        rm -f "$tmpfile"
+    download_to_file "$URL" "$tmpfile" "$http_proxy_address"
+
+    if [ $? -ne 0 ] || [ ! -s "$tmpfile" ]; then
+        log "Download $service list failed" "error"
         return 1
-    }
+    fi
 
     subnets="$(parse_domain_or_subnet_file_to_comma_string "$tmpfile" "subnets")"
     rm -f "$tmpfile"
-
-    [ -z "$subnets" ] && return 0
 
     if [ "$service" = "discord" ]; then
         nft_add_set_elements "$NFT_TABLE_NAME" "$NFT_DISCORD_SET_NAME" "$subnets"
